version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      express-mongo:
        ipv4_address: 172.16.238.10

  backend:
    restart: always
    build:
      context: app
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    environment:
      MONGODB_URL: mongodb://mongodb:27017/myapp
    networks:
      - express-mongo
      - express
    ports: 
      - "3001:3001"

networks:
  express-mongo:
    ipam:
      config:
        - subnet: 172.16.238.0/24
  express: